### ISSUE TITLE
[FEATURE] Create a Code Coverage Action

### ISSUE THREAD

**Issue by khushalbhardwaj-0111** [Curewell-Homeo-Clinic/admin-system#63]
### Description

Create a `CodeCov` integration github action to send code coverage to codecov and also post the coverage of the pr in the comments.

### Screenshots

Something like this:
![Screenshot from 2021-12-25 19-39-34](https://user-images.githubusercontent.com/76873719/147386784-beff6620-03ef-4420-a4fc-8db7a6416b35.png)

**Comment by reshu-saidawat** [comment]
Fixed with #64
